# Generated by Django 4.2 on 2023-06-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('From', models.CharField(default='0', max_length=50)),
                ('To', models.CharField(default='0', max_length=50)),
                ('timefrom', models.CharField(max_length=50)),
                ('timeto', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
    ]
