# Generated by Django 4.2 on 2023-06-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
