# Generated by Django 4.2 on 2023-07-05 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_alter_contact_email_alter_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('From', models.CharField(default='0', max_length=50)),
                ('To', models.CharField(default='0', max_length=50)),
                ('timefrom', models.CharField(max_length=50)),
                ('timeto', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(max_length=50)),
                ('seatno', models.IntegerField(default=0)),
                ('username', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
