# Generated by Django 4.2 on 2023-07-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
