# Generated by Django 4.2 on 2023-07-09 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_book_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='duration',
        ),
    ]
