# Generated by Django 4.2 on 2023-07-14 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_bus_seatno_bus_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='From',
        ),
        migrations.RemoveField(
            model_name='book',
            name='To',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='timefrom',
        ),
        migrations.RemoveField(
            model_name='book',
            name='timeto',
        ),
        migrations.AddField(
            model_name='book',
            name='aFrom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bFrom', to='home.bus'),
        ),
        migrations.AddField(
            model_name='book',
            name='aTo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bTo', to='home.bus'),
        ),
        migrations.AddField(
            model_name='book',
            name='adate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bdate', to='home.bus'),
        ),
        migrations.AddField(
            model_name='book',
            name='aname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bname', to='home.bus'),
        ),
        migrations.AddField(
            model_name='book',
            name='aprice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bprice', to='home.bus'),
        ),
        migrations.AddField(
            model_name='book',
            name='atimefrom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='btimefrom', to='home.bus'),
        ),
        migrations.AddField(
            model_name='book',
            name='atimeto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='btimeto', to='home.bus'),
        ),
    ]
