# Generated by Django 4.2 on 2023-07-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_afrom_book_from_rename_ato_book_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='From',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='To',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='timefrom',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='timeto',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
