# Generated by Django 4.2 on 2023-07-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_book_from_alter_book_to_alter_book_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tp',
            field=models.IntegerField(default=0),
        ),
    ]
