# Generated by Django 4.2 on 2023-07-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_book_tp'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='busid',
            field=models.IntegerField(default=0),
        ),
    ]
